name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - WowLoginMessages-v[0-9]+.*
      - WowWorldMessages-v[0-9]+.*

jobs:
  login:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/WowLoginMessages-v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: dotnet test
      - run: dotnet pack -c Release
      - run: cd WowLoginMessages/bin/Release &&  dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }}  -s https://api.nuget.org/v3/index.json
  world:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/WowWorldMessages-v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: dotnet test
      - run: dotnet pack -c Release
      - run: cd WowWorldMessages/bin/Release &&  dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }}  -s https://api.nuget.org/v3/index.json
